- stock_capability/README.md
This PR fixes a tiny formatting error in the readme for the stock capability example.
> Fix error in stock_capability readme

- inmemory-streams/Cargo.toml
- inmemory-streams/src/lib.rs
- keyvalue-provider/Cargo.toml
- keyvalue-provider/src/lib.rs
Updated names of crates as well to bring to parity with other capability providers, and bumped versions to `0.2.1`. If this doesn't fit the versioning standard, I can change that.
> Implement static capability feature for keyvalue and inmemory streams

- echo/Cargo.lock
- echo/Cargo.toml
- echo/README.md
- kvcounter-as/assembly/index.ts
- kvcounter-as/package-lock.json
- kvcounter-as/package.json
- kvcounter-as/sign.sh
- kvcounter-as/tsconfig.json
- kvcounter/Cargo.lock
- kvcounter/Cargo.toml
- kvcounter/README.md
Part of #5 
This PR updates the `echo`, `kvcounter` and `kvcounter-as` actors to use the applicable `wasmcloud:*` contract IDs, and replaces their dependencies of `wascc_actor` with the appropriate actor-interfaces for the examples. I have verified that `echo` and `kvcounter` are working well to replace their counterparts, however `kvcounter-as` is not yet in a working state. Creating a draft PR for now, I'll convert to a regular PR once I get the assemblyscript KVCounter actor working.
> Updating actors echo, kvcounter and kvcounter-as to interfaces and wasmcloud contract

- echo/Cargo.toml
The driving reason for this PR is my desire to test updating actors with `wash ctl`, so I'd like to release a new patch version of `echo` with the newest versions of actor interfaces as well.
> Bumping to 0.2.1 with newest interfaces

- .github/workflows/echo-release.yml
- .github/workflows/extras-release.yml
- .github/workflows/extras.yml
- .github/workflows/keyvalue-provider-release.yml
- .github/workflows/kvcounter-as-release.yml
- .github/workflows/kvcounter-release.yml
- .github/workflows/logger-release.yml
- .github/workflows/subscriber-release.yml
- .github/workflows/template-release.yml
Turns out the extras example didn't have a release template so I couldn't release it 😄 
While I was editing them I went ahead and made it so that the release actions had to pass cargo checks and clippy checks before the release would occur.
> Examples templates require passing build before release, included extras template

- ecommerce/payments-interface/Makefile
- ecommerce/payments-interface/codegen.yaml
The payments interface generator example did not work with the latest version of wapc.
> fixed payments interface issue

- actor/echo/Cargo.lock
- actor/echo/Cargo.toml
- actor/echo/Makefile
- actor/echo/src/lib.rs
Previously the echo actor would simply echo back an empty vec, but we should echo the body back too. This was causing test failures in https://github.com/wasmCloud/wasmcloud-otp/pull/214
> Echo body back, increment revision

- build/makefiles/actor.mk
fixes [wash 170](https://github.com/wasmCloud/wash/issues/170)
adds support for call alias
(define ACTOR_ALIAS in Makefile)
adds support for actor name
(define ACTOR_NAME in Makefile), defaults to PROJECT if undefined
> add makefile support for call aliases and custom actor name

- docker/docker-compose_without-host.yml
This PR adds `wasmcloud_host` to the list of images in the default `docker-compose.yml` so that we are able to automatically run a host with examples. This is also used in the documentation, and a PR will follow to update the dev site.
> Add wasmcloud image to docker compose

- actor/echo-messaging/Makefile
- actor/xkcd/Makefile
- build/makefiles/actor.mk
- build/makefiles/provider.mk
- petclinic/actors/clinicapi/actor.mk
- petclinic/actors/visits/actor.mk
- petclinic/petclinic-interface/rust/src/petclinic.rs
- petclinic/run.sh
Related to a naming convention change a week ago:
https://github.com/wasmCloud/wash/pull/198
I ran `make && make test` locally.
This regenerated petclinic.rs file. I opted to keep it, but
holler if this needs to be a separate PR.
> fix: timeout and rpc-timeout changed to ms

- petclinic/actors/clinicapi/src/lib.rs
- petclinic/actors/customers/src/db.rs
- petclinic/actors/customers/src/lib.rs
- petclinic/actors/vets/src/db.rs
- petclinic/actors/visits/src/db.rs
Fixed all clippy warnings for the various rust modules within the petclinic example.
I noticed that there isn't a github workflow for this project. Looking at the template, I would need the ability to create a secret for this org to create a working action workflow (`secrets.WASMCLOUD_EXAMPLE`). I skipped this but it would be worth doing, at least for the rust-check with clippy.
> fix(petclinic): clippy warnings

- petclinic/actors/customers/Cargo.toml
- petclinic/actors/customers/src/db.rs
- petclinic/actors/visits/Cargo.toml
- petclinic/actors/visits/src/db.rs
- petclinic/petclinic-interface/rust/src/petclinic.rs
- petclinic/petclinic-interface/visits.smithy
- petclinic/petclinic-ui/package-lock.json
- petclinic/petclinic-ui/src/Modal.js
- petclinic/petclinic-ui/src/Owner.js
- petclinic/petclinic-ui/src/Owners.js
- petclinic/petclinic-ui/src/PetTypes.js
- petclinic/petclinic-ui/src/Vets.js
This PR addresses a number of miscellaneous potential errors that you could encounter across the petclinic example
1. 500 errors editing a pet due to missing an owner ID
2. 500 errors adding a visit due to not including an owner ID (interface updated)
3. UI crashes when typing dates due to NaN errors
4. Incorrect shape of `pet.petType` state, would cause the pet type to be incorrectly selected after first creation in `Edit Pet`
5. When customers or vets actors are down, react would crash. Now we handle that case and simply display an empty table
Lastly, I addressed a few warnings for unused `response` variables
> Fix petclinic 500 errors and UI crashes

- .github/workflows/petclinic.yml
- petclinic/Makefile
- petclinic/actors/clinicapi/Cargo.toml
- petclinic/actors/clinicapi/src/lib.rs
- petclinic/actors/customers/src/db.rs
- petclinic/actors/vets/Cargo.toml
- petclinic/petclinic-interface/rust/Cargo.toml
- petclinic/petclinic-interface/rust/src/petclinic.rs
Our petclinic demo is getting increasingly refined and popular, starting this PR to get a proper build/test/release pipeline prepared for the actors used in the demo.
This PR includes actions to:
1. Build, format check, lint, test, and sign all four actors involved in the petclinic demo with a matrix strategy
2. Build, format check, lint, and test the petclinic interface
3. Build the UI, check for warnings and errors
4. Create a Github release with our signed petclinic actors attached
5. Release signed actors to AzureCR
**NOTE** The way the release action is setup is such that each tag will release _all_ actors involved in the demo. This is for simplicity, and so if an actor's version in `Cargo.toml` is not changed then it will be re-published to the existing tag. I would recommend just …
> Petclinic CI/CD

- actor/echo/README.md
- actor/echo/wadm.yaml
- actor/kvcounter/wadm.yaml
- petclinic/.gitignore
- petclinic/docker/docker-compose.yml
- petclinic/run.sh
- petclinic/wadm.yaml
Note that this purposefully doesn't add full documentation to READMEs
because setting up wadm is an extra step right now. Once we add support
for it in `wash up` by default, we can add the instructions for running
in wadm. As an intermediate step, instructions were added as a comment
to the top of the wadm manifests
> feat(*): Adds wadm examples for our most commonly used example actors

- petclinic/run.sh
Adds a start-actors command to `run.sh` start all of the default petclinic actors.
Signed-off-by: Matt Wilkinson <matt@mattwilkinson.dev>
> Add `./run.sh start-actors` command

- actor/animal-image-downloader/README.md
The blobstore_fs ociref is an underscore, not a dash
> Fixed blobstore_fs ociref

- actor/animal-image-downloader/README.md
Simply a polish of the instructions that lets a user run this example with _only_ wash
> Add `wash call` to the animal example to remove NATS CLI as a prereq

- configservice/Cargo.lock
- configservice/Cargo.toml
- configservice/src/main.rs
This adds `registryType` to `Credential`, which is a required field on the interface now: https://github.com/wasmCloud/interfaces/blob/main/configservice/config-service.smithy#L72
Signed-off-by: Connor Smith <connor@cosmonic.com>
> add registryType to Credential

- petclinic/actors/ui/src/Modal.js
Fixes https://github.com/wasmCloud/examples/issues/134 by initially populating all `owner` fields with empty strings.
> Uses defaults to avoid persisting undefined values.

- actor/animal-image-downloader/wadm.yaml
- actor/blobby/wadm.yaml
- actor/echo-messaging/wadm.yaml
- actor/hello/wadm.yaml
- actor/kvcounter/wadm.yaml
- actor/message-pub/README.md
- actor/message-pub/wadm.yaml
- actor/policy/wadm.yaml
- actor/random/wadm.yaml
- actor/todo/wadm.yaml
- actor/xkcd/wadm.yaml
- petclinic/wadm.yaml
This PR adds `wadm.yaml` manifests for each example so that you can use wadm to easily run them. This PR is purely meant to be additive, doesn't add manifests for actors that are not published to an OCI repo, and doesn't update the README quite yet as wadm is still in alpha state.
N/A
N/A
I ran each manifest to make sure wadm could start the resources 😄
> wadm manifests for each actor example

- leaderboard/src/lib.rs
This API is made to demonstrate interactivity with a web client (amongst others) so we need a CORS header. The JSON header is purely optional, but it helps with apps like Postman.
None
`next`
Consumers of the API can now use web browser clients
Works on my machine
> Add JSON and CORS headers to requests

- .github/workflows/pinger.yml
- .github/workflows/ponger.yml
This PR removes the `make` from the pinger/ponger actions in favor of wash build
> Removed make in favor of wash build

- actor/blobby/actor/Cargo.lock
- actor/blobby/actor/Cargo.toml
Uses the new version that doesn't use cbor for better compatibility with the new rust host
> chore(blobby): Update blobby to use new interface version

- actor/kvcounter-wasmcon2023/Cargo.toml
- actor/kvcounter-wasmcon2023/src/lib.rs
For some reason the pinned build we've been using of wit-bindgen started to fail. I updated to a slightly more recent rev which fixes the issue. This also fixed a few small items I found while manually validating that all of this worked
> fix(kvcounter): Fixes issue with pinned wit-bindgen dep

- actor/actor-to-actor/README.md
- actor/actor-to-actor/wadm.yaml
This PR removes a failing operation in a README (see https://github.com/wasmCloud/wasmCloud/issues/629) and updates the wadm manifest to properly link pinger to httpserver.
https://github.com/wasmCloud/wasmCloud/issues/629
N/A
It works!
> fix(a2a): fix wadm for pingerponger

- actor/kvcounter-wasmcon2023/README.md
- actor/kvcounter-wasmcon2023/src/lib.rs
This adds use of `wasi:keyvalue/atomic` for doing atomic increments in the kvcounter example 
Resolves #229 
Tested locally with the new Rust host (`wash` > v0.19)
The instructions show the old UI, but doing all setup with `wash` CLI works
> feat: use atomic increment for kvcounter

- docker/docker-compose.yml
- docker/docker-compose_without-host.yml
- petclinic/docker/docker-compose.yml
This updates our docker-compose files to use more recent versions of NATS, the wasmCloud host, and wadm
Resolves https://github.com/wasmCloud/examples/issues/240
Tested manually with `docker compose up`. Confirmed each of the services ran and was able to deploy a wadm manifest successfully
> chore: update docker-compose files

- README.md
This updates the README to distinguish between the stable and experimental ABIs
For a preview of the changes, see https://github.com/connorsmith256/examples/tree/chore/update-readme
> chore: add note about differences between stable and experimental ABIs
