.github/workflows/kvcounter-as-release.yml, .github/workflows/kvcounter-release.yml
Adds github actions for `kvcounter` and `kvcounter-as`
=> Initial add of github actions

extras/src/lib.rs
Now that we require `cargo check` before release, and when I PRed in the extras actor we didn't have the action to build it, the release failed because the formatting was bad.
I'm trying to tell myself that CICD is good, but three PRs are testing my ability to stay optimistic.
=> Formatted extras actor

README.md
4th PR, too many moving pieces, too small 🧠
=> Add extras OCI reference to README

wasmcloud-chat/actors/broker-channel/src/lib.rs, wasmcloud-chat/actors/messages/src/lib.rs, wasmcloud-chat/actors/telnet-channel/Cargo.lock, wasmcloud-chat/actors/telnet-channel/Cargo.toml, wasmcloud-chat/actors/telnet-channel/Makefile, wasmcloud-chat/actors/telnet-channel/manifest.yaml, wasmcloud-chat/actors/telnet-channel/src/lib.rs, wasmcloud-chat/ops/allin1-manifest.yaml
Initial working IMPL of the telnet channel actor
=> [wcchat] Telnet channel actor

docker/docker-compose.yml
we needed a sample docker-compose file
=> add docker-compose example

actor/todo/.cargo/config.toml, actor/todo/.gitignore, actor/todo/Cargo.toml, actor/todo/Makefile, actor/todo/README.md, actor/todo/src/lib.rs
This is the example that we will be using in our demo.
I can make a second PR once https://github.com/wasmCloud/interfaces/pull/10 is merged and released, or we can leave this PR open until then (this won't block anything on our side).
=> port todo example to otp

.github/workflows/TEMPLATE_actor.yml, .github/workflows/echo-messaging.yml, .github/workflows/echo.yml, .github/workflows/example-logging.yml, .github/workflows/factorial.yml, .github/workflows/hello.yml, .github/workflows/kvcounter.yml, .github/workflows/payments.yml, .github/workflows/random.yml, .github/workflows/todo.yml, .github/workflows/xkcd.yml, actor/echo/Cargo.toml
=> Remaining CI/CD for examples

provider/factorial/Cargo.lock, provider/factorial/Cargo.toml, provider/factorial/src/main.rs
=> second try - factorial use derive macro

interface/payments/rust/Cargo.toml, interface/runner/rust/Cargo.toml
=> update wasmbus-rpc in examples/interface

.github/workflows/runner.yml
=> make workflow name match crate name

petclinic/README.md, petclinic/actors/clinicapi/README.md, petclinic/actors/customers/README.md, petclinic/actors/vets/README.md, petclinic/actors/visits/README.md, petclinic/petclinic-interface/README.md, petclinic/petclinic-interface/rust/README.md, petclinic/petclinic-interface/rust/src/petclinic.rs
=> Initial documentation via READMEs

build/makefiles/provider.mk
=> move new rules lower so they don't override default rule

petclinic/actors/clinicapi/src/lib.rs, petclinic/petclinic-interface/rust/src/petclinic.rs
=> Adding pet type object to pets list and pet details

README.md, actor/README.md, docker/README.md, interface/README.md, pre-otp/README.md, provider/README.md
=> Updating README coverage

petclinic/actors/clinicapi/src/lib.rs
=> Fixing deserialization bug

README.md
=> update README with all current examples

petclinic/actors/customers/src/db.rs, petclinic/actors/visits/src/db.rs
=> Fixing SQL statements

petclinic/run.sh
=> fix macos-v-linux issues in run.sh

build/makefiles/provider.mk
=> Scripted first par target, allow configuration

actor/echo-messaging/Cargo.lock, actor/echo-messaging/Cargo.toml, actor/echo-messaging/Makefile, actor/echo/Cargo.lock, actor/echo/Cargo.toml, actor/echo/Makefile, actor/echo/src/lib.rs, actor/hello/Cargo.lock, actor/hello/Cargo.toml, actor/hello/Makefile, actor/kvcounter/Cargo.lock, actor/kvcounter/Cargo.toml, actor/kvcounter/Makefile, actor/logging/Cargo.lock, actor/logging/Cargo.toml, actor/logging/Makefile, actor/random/Cargo.lock, actor/random/Cargo.toml, actor/random/Makefile, actor/todo-sql/Cargo.toml, actor/todo-sql/Makefile, actor/todo/Cargo.toml, actor/todo/Makefile, actor/xkcd/Cargo.lock, actor/xkcd/Cargo.toml, actor/xkcd/Makefile, petclinic/actors/visits/Cargo.lock, petclinic/petclinic-interface/rust/src/petclinic.rs
=> Ensured example actors have human friendly names

docker/docker-compose.yml
=> updated example compose nats version for security

interface/unions/codegen.toml, interface/unions/rust/Cargo.toml, interface/unions/rust/src/lib.rs, interface/unions/rust/src/smithy_types.rs, interface/unions/rust/src/union_demo.rs, interface/unions/smithy-types.smithy, interface/unions/union-demo.smithy
=> fix floats in unions; add smithy-types tests

build/makefiles/actor.mk, provider/Makefile, provider/python/.gitignore, provider/python/Cargo.toml, provider/python/Makefile, provider/python/README.md, provider/python/provider_test_config.toml, provider/python/src/config.rs, provider/python/src/lib.rs, provider/python/src/main.rs, provider/python/src/pime.rs, provider/python/tests/__init__.py, provider/python/tests/call_service.rs, provider/python/tests/dispatch.py, provider/python/tests/pprov_test.rs
=> initial checkin, Python capability provider

petclinic/actors/ui/Cargo.lock, petclinic/actors/ui/Cargo.toml, petclinic/actors/ui/package-lock.json, petclinic/actors/ui/package.json, petclinic/actors/ui/src/Api.js, petclinic/actors/ui/tailwind.config.js
Signed-off-by: Connor Smith <connor@cosmonic.com>
=> update UI actor to purge unused CSS files and connect to API via current browser location

.github/workflows/dogs-and-cats.yml
=> corrected artifact name for dogs/cats

ngs/dogs-and-cats/README.md
another assumption about the resulting OCIref, now it's correct 😄
=> Correcting dogs-and-cats OCI ref

docker/docker-compose.yml
@snnsnn This should fix #166, would you mind giving it a try with your setup?
=> Set wasmCloud to depend on other services before starting

actor/xkcd/src/lib.rs
We were over a year behind in xkcd comics!  Fixed it.
=> Now with 8.2% more humor!

.github/workflows/kvcounter.yml
Yet another fix for kvcounter that I'm actually testing in the PR first
=> Replaced make with wash build for kvcounter

petclinic/create_data.sql
=> Added Cinza to petclinic

crypto/signature-demo.md, crypto/verify/Cargo.toml, crypto/verify/src/lib.rs
=> simplify code by removing Error enum

actor/logging/Makefile, actor/random/Makefile
make targets weren't working #210 
n/a
fixed examples
ran locally
n/a
n/a
=> fix wash call for random+logging actor examples

leaderboard/src/lib.rs
Leaderboard actor will keep creating new leaderboards if the same key is used in a POST request.
Example blog post may need to be updated with new content.
Tested manually, but not sure on how to write any other tests (or if they are necessary)
=> Only create new leaderboards if none already exist

actor/echo-wasi-preview2/Cargo.toml
Remove the commented old dep for `wasmcloud-actor`
=> fix: remove old wasmcloud-actor crate dep

actor/kvcounter-wasmcon2023/src/lib.rs
A few changes:
- Fix some nits pointed out by @thomastaylor312  (thanks for the review!)
- Update `wit-bindgen` to newer published version, adapt it (some code changes were required due to upstream)
=> fix: wasmcon2023 kvcounter fixes

.github/workflows/TEMPLATE_actor.yml, .github/workflows/TEMPLATE_provider.yml, .github/workflows/animal-image-downloader.yml, .github/workflows/blobby.yml, .github/workflows/dogs-and-cats.yml, .github/workflows/echo-messaging.yml, .github/workflows/echo.yml, .github/workflows/example-logging.yml, .github/workflows/factorial.yml, .github/workflows/hello.yml, .github/workflows/ifconfig.yml, .github/workflows/kvcounter-tinygo.yml, .github/workflows/kvcounter.yml, .github/workflows/message-pub.yml, .github/workflows/payments.yml, .github/workflows/petclinic.yml, .github/workflows/pinger.yml, .github/workflows/policy.yml, .github/workflows/ponger.yml, .github/workflows/random.yml, .github/workflows/runner.yml, .github/workflows/todo.yml, .github/workflows/xkcd.yml
=> ci: update actions
